apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: my-app
  source:
    repoURL: https://github.com/flaviorssilva1981/guiadodevops.git
    targetRevision: main
    path: kubernetes/argocd_cluster02/config/boutique-app
  destination:
    server: https://kubernetes.default.svc
    namespace: boutique
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true       
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
