apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boutique-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
    external-dns.alpha.kubernetes.io/hostname: boutique.dublinconsulting.com.br
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  tls:
    - hosts:
        - boutique.dublinconsulting.com.br
      secretName: tls-boutique
  rules:
    - host: boutique.dublinconsulting.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
