apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-rollouts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  project: tools
  source:
    repoURL: https://github.com/flaviorssilva1981/guiadodevops.git
    targetRevision: main
    path: kubernetes/argocd_cluster02/config/tools/argocd-rollouts-config
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /status
    - /metadata/annotations
    - /metadata/labels
    - /spec/conversion
    - /spec/preserveUnknownFields
    - /spec/versions/0/additionalPrinterColumns
    - /spec/versions/0/schema/openAPIV3Schema
    - /spec/versions/1/additionalPrinterColumns
    - /spec/versions/1/schema/openAPIV3Schema
    - /spec/versions/2/additionalPrinterColumns
    - /spec/versions/2/schema/openAPIV3Schema
    - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true       
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
