apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: my-app
  source:
    repoURL: https://github.com/flaviorssilva1981/guiadodevops.git
    targetRevision: main
    path: kubernetes/argocd_cluster02/config/my-k8s-app/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true       
      selfHeal: true
